"""add chat_messages table

Revision ID: 2ee1167b316f
Revises: 578e2080823f
Create Date: 2025-05-29 08:51:40.496906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee1167b316f'
down_revision: Union[str, None] = '578e2080823f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grup_id', sa.Integer(), nullable=True),
    sa.Column('sender_nim', sa.String(), nullable=False),
    sa.Column('teks', sa.Text(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grup_id'], ['grup.id'], name=op.f('fk_chat_messages_grup_id_grup')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
