"""add jadwal_kuliah table

Revision ID: 81e87b3cce72
Revises: 87682a11597e
Create Date: 2025-05-26 19:34:45.796060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e87b3cce72'
down_revision: Union[str, None] = '87682a11597e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jadwal_kuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(), nullable=False),
    sa.Column('jam_mulai', sa.String(), nullable=False),
    sa.Column('jam_selesai', sa.String(), nullable=False),
    sa.Column('matkul', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jadwal_kuliah_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jadwal_kuliah'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jadwal_kuliah')
    # ### end Alembic commands ###
