"""add grup and grup_anggota

Revision ID: 845170f3fc85
Revises: 81e87b3cce72
Create Date: 2025-05-26 19:55:50.387970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845170f3fc85'
down_revision: Union[str, None] = '81e87b3cce72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_grup_admin_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grup'))
    )
    op.create_table('grup_anggota',
    sa.Column('grup_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grup_id'], ['grup.id'], name=op.f('fk_grup_anggota_grup_id_grup')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_grup_anggota_user_id_users')),
    sa.PrimaryKeyConstraint('grup_id', 'user_id', name=op.f('pk_grup_anggota'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grup_anggota')
    op.drop_table('grup')
    # ### end Alembic commands ###
