"""add kolom jadwal

Revision ID: a9d4e4eeec30
Revises: 572a1aab7810
Create Date: 2025-06-02 20:20:10.476031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d4e4eeec30'
down_revision: Union[str, None] = '572a1aab7810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grup', sa.Column('jadwal', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grup', 'jadwal')
    # ### end Alembic commands ###
