"""create ajakan table

Revision ID: baeea7eb5d45
Revises: 272463fcac04
Create Date: 2025-05-29 09:11:40.815041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baeea7eb5d45'
down_revision: Union[str, None] = '272463fcac04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajakan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dari_user_id', sa.Integer(), nullable=True),
    sa.Column('ke_user_id', sa.Integer(), nullable=True),
    sa.Column('grup_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dari_user_id'], ['users.id'], name=op.f('fk_ajakan_dari_user_id_users')),
    sa.ForeignKeyConstraint(['grup_id'], ['grup.id'], name=op.f('fk_ajakan_grup_id_grup')),
    sa.ForeignKeyConstraint(['ke_user_id'], ['users.id'], name=op.f('fk_ajakan_ke_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ajakan'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ajakan')
    # ### end Alembic commands ###
