"""Initial schema

Revision ID: 18bf4e7653fb
Revises: 
Create Date: 2025-06-02 21:38:11.879797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bf4e7653fb'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('nama_lengkap', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('nim', name=op.f('uq_users_nim'))
    )
    op.create_table('grup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('jadwal', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_grup_admin_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grup'))
    )
    op.create_table('jadwal_kuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(), nullable=False),
    sa.Column('jam_mulai', sa.String(), nullable=False),
    sa.Column('jam_selesai', sa.String(), nullable=False),
    sa.Column('matkul', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jadwal_kuliah_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jadwal_kuliah'))
    )
    op.create_table('ajakan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dari_user_id', sa.Integer(), nullable=True),
    sa.Column('ke_user_id', sa.Integer(), nullable=True),
    sa.Column('grup_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dari_user_id'], ['users.id'], name=op.f('fk_ajakan_dari_user_id_users')),
    sa.ForeignKeyConstraint(['grup_id'], ['grup.id'], name=op.f('fk_ajakan_grup_id_grup')),
    sa.ForeignKeyConstraint(['ke_user_id'], ['users.id'], name=op.f('fk_ajakan_ke_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ajakan'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grup_id', sa.Integer(), nullable=True),
    sa.Column('sender_nim', sa.String(), nullable=False),
    sa.Column('teks', sa.Text(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grup_id'], ['grup.id'], name=op.f('fk_chat_messages_grup_id_grup')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_table('grup_anggota',
    sa.Column('grup_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grup_id'], ['grup.id'], name=op.f('fk_grup_anggota_grup_id_grup')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_grup_anggota_user_id_users')),
    sa.PrimaryKeyConstraint('grup_id', 'user_id', name=op.f('pk_grup_anggota'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grup_anggota')
    op.drop_table('chat_messages')
    op.drop_table('ajakan')
    op.drop_table('jadwal_kuliah')
    op.drop_table('grup')
    op.drop_table('users')
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    # ### end Alembic commands ###
